project:
  resources:
    - "Resources"
  type: website
  output-dir: dabrion

website:
  title: "Dabrion"


format:
  html:
    theme: 
          light: [flatly,./styles.scss]
    css: styles.css
    toc: false


