project:
  resources:
    - "Resources"
  type: website
  output-dir: dabrion

website:
  title: "Dabrion"
  navbar:
    left:
      - href: https://marion-alexandre.freeboxos.fr
        text: Dabrion's cloud
      - href: receipes_list.qmd
        text: Recettes

format:
  html:
    theme: 
          light: [flatly,./styles.scss]
    css: styles.css
    toc: false


